INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0001','Articulos de belleza');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0002','Cuidado personal');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0003','Articulos de papeleria');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0004','Articulos de limpieza');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0005','Cuidado de mascotas');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0006','Alimentos');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0007','Electrodomésticos');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0008','Hortalizas');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0009','Medicinas');
INSERT INTO "lineas" (cod_linea,descripcion) VALUES ('L0010','Licor');